2020-06-19 13:55:23,540:DEBUG:certbot.main:certbot version: 0.30.2
2020-06-19 13:55:23,541:DEBUG:certbot.main:Arguments: ['--non-interactive', '--config', '/etc/letsencrypt.ini', '--cert-name', 'npm-1', '--agree-tos', '--email', 'tmvp91@gmail.com', '--preferred-challenges', 'dns,http', '--webroot', '--domains', '134.209.199.249:8443']
2020-06-19 13:55:23,542:DEBUG:certbot.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#manual,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
2020-06-19 13:55:23,556:DEBUG:certbot.log:Root logging level set at 20
2020-06-19 13:55:23,557:INFO:certbot.log:Saving debug log to /config/log/letsencrypt/letsencrypt.log
2020-06-19 13:55:23,557:DEBUG:certbot.plugins.selection:Requested authenticator webroot and installer None
2020-06-19 13:55:23,561:DEBUG:certbot.plugins.selection:Single candidate plugin: * webroot
Description: Place files in webroot directory
Interfaces: IAuthenticator, IPlugin
Entry point: webroot = certbot.plugins.webroot:Authenticator
Initialized: <certbot.plugins.webroot.Authenticator object at 0x7fd5c3ef5a58>
Prep: True
2020-06-19 13:55:23,562:DEBUG:certbot.plugins.selection:Selected authenticator <certbot.plugins.webroot.Authenticator object at 0x7fd5c3ef5a58> and installer None
2020-06-19 13:55:23,562:INFO:certbot.plugins.selection:Plugins selected: Authenticator webroot, Installer None
2020-06-19 13:55:23,712:DEBUG:acme.client:Sending GET request to https://acme-v02.api.letsencrypt.org/directory.
2020-06-19 13:55:23,714:DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): acme-v02.api.letsencrypt.org
2020-06-19 13:55:24,211:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "GET /directory HTTP/1.1" 200 658
2020-06-19 13:55:24,212:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Fri, 19 Jun 2020 13:55:24 GMT
Content-Type: application/json
Content-Length: 658
Connection: keep-alive
Cache-Control: public, max-age=0, no-cache
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "Xg6uh1aKEP4": "https://community.letsencrypt.org/t/adding-random-entries-to-the-directory/33417",
  "keyChange": "https://acme-v02.api.letsencrypt.org/acme/key-change",
  "meta": {
    "caaIdentities": [
      "letsencrypt.org"
    ],
    "termsOfService": "https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf",
    "website": "https://letsencrypt.org"
  },
  "newAccount": "https://acme-v02.api.letsencrypt.org/acme/new-acct",
  "newNonce": "https://acme-v02.api.letsencrypt.org/acme/new-nonce",
  "newOrder": "https://acme-v02.api.letsencrypt.org/acme/new-order",
  "revokeCert": "https://acme-v02.api.letsencrypt.org/acme/revoke-cert"
}
2020-06-19 13:55:24,213:DEBUG:acme.client:Requesting fresh nonce
2020-06-19 13:55:24,213:DEBUG:acme.client:Sending HEAD request to https://acme-v02.api.letsencrypt.org/acme/new-nonce.
2020-06-19 13:55:24,336:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "HEAD /acme/new-nonce HTTP/1.1" 200 0
2020-06-19 13:55:24,337:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Fri, 19 Jun 2020 13:55:24 GMT
Connection: keep-alive
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: 0102pkeejttI4tRfRSpV988xMVpcbS0Q6mHBctmfGDRLPM8
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800


2020-06-19 13:55:24,337:DEBUG:acme.client:Storing nonce: 0102pkeejttI4tRfRSpV988xMVpcbS0Q6mHBctmfGDRLPM8
2020-06-19 13:55:24,338:DEBUG:acme.client:JWS payload:
b'{\n  "contact": [\n    "mailto:tmvp91@gmail.com"\n  ],\n  "termsOfServiceAgreed": true,\n  "resource": "new-reg"\n}'
2020-06-19 13:55:24,343:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/new-acct:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAiandrIjogeyJuIjogIm1yVUpmQzV3ZGZHZTNpVU1jNGRqWVZ1Zy1yak1JTTZMdHdqR3NCbWJOLTNxcGl5R1paNkhCMUFtNUJRcFZYZXpHeEtVeXJVc0diQVVBSXcybk9RNW14Qkdwd0lSeC1wamdqYWVrZFdrM2RYUkg4U0RpNUlJbm5LODdCYm1ib1RfT1JBR0NvVmI1Y2dkaG52cjlBUTZlTWJuY19QRHFUTjJ6OFh3dUQwYk1fYTFGVnFhNnIwUEZkTFNXWWRnZXpJSHVTU3lkcUNVb1lxQm1tbjBBQnVhaU9yWUdJX2JGcTNxU0NlN2tMMWtCQlpmU2NtZkxmOUctQ2x2T3VQMWN6dnowcUhSdmVpU1JJWmp4Um9QTHA4SV94NWMxVG96TGIweUdHaEJUYlhXeXYwOXBtN2E0TGZaQ0tmRnJMcXhUdWZtZVN4LVBKVVlzY05ONjk1WHZNTGh1USIsICJlIjogIkFRQUIiLCAia3R5IjogIlJTQSJ9LCAibm9uY2UiOiAiMDEwMnBrZWVqdHRJNHRSZlJTcFY5ODh4TVZwY2JTMFE2bUhCY3RtZkdEUkxQTTgiLCAidXJsIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL25ldy1hY2N0In0",
  "signature": "gyk3VR-0V1p5F5yHHJNT6fO7mgzn2GdAgHyTm1PTel_HVVXl75h8j5myg_EeKjjmwOIXvGuuoKo40EevLXQyBp2gFr0bAlgbrg7zLSgaQT3FLntaDI9DerLMtLle_EJGeJvfXpEeEK1a3T6mqid2KZ5XU25IXtatj1ItHOme9xd9nQz_WrsUJLrK2NiXIRDXdI0aTg23P8LJ9IyMepiM1WM0V57MBC0G6esj5DI5G4AKi-HNsSLR3WbQRgCebFPNXdLbFDOTv21tqEyU27lh_CBaP3M0MPPGTE1NLuWKtLzVEeE7XdpyPnIS9hlGH28IICnJx1aHrWqUEKK-awjxdw",
  "payload": "ewogICJjb250YWN0IjogWwogICAgIm1haWx0bzp0bXZwOTFAZ21haWwuY29tIgogIF0sCiAgInRlcm1zT2ZTZXJ2aWNlQWdyZWVkIjogdHJ1ZSwKICAicmVzb3VyY2UiOiAibmV3LXJlZyIKfQ"
}
2020-06-19 13:55:24,537:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/new-acct HTTP/1.1" 201 561
2020-06-19 13:55:24,538:DEBUG:acme.client:Received response:
HTTP 201
Server: nginx
Date: Fri, 19 Jun 2020 13:55:24 GMT
Content-Type: application/json
Content-Length: 561
Connection: keep-alive
Boulder-Requester: 89244674
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index", <https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf>;rel="terms-of-service"
Location: https://acme-v02.api.letsencrypt.org/acme/acct/89244674
Replay-Nonce: 0102ANd9tVNKIyHSPY3IfMHPrnp2lIHpFHKlVnmVZeKUydo
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "key": {
    "kty": "RSA",
    "n": "mrUJfC5wdfGe3iUMc4djYVug-rjMIM6LtwjGsBmbN-3qpiyGZZ6HB1Am5BQpVXezGxKUyrUsGbAUAIw2nOQ5mxBGpwIRx-pjgjaekdWk3dXRH8SDi5IInnK87BbmboT_ORAGCoVb5cgdhnvr9AQ6eMbnc_PDqTN2z8XwuD0bM_a1FVqa6r0PFdLSWYdgezIHuSSydqCUoYqBmmn0ABuaiOrYGI_bFq3qSCe7kL1kBBZfScmfLf9G-ClvOuP1czvz0qHRveiSRIZjxRoPLp8I_x5c1TozLb0yGGhBTbXWyv09pm7a4LfZCKfFrLqxTufmeSx-PJUYscNN695XvMLhuQ",
    "e": "AQAB"
  },
  "contact": [
    "mailto:tmvp91@gmail.com"
  ],
  "initialIp": "134.209.199.249",
  "createdAt": "2020-06-19T13:55:24.500976223Z",
  "status": "valid"
}
2020-06-19 13:55:24,538:DEBUG:acme.client:Storing nonce: 0102ANd9tVNKIyHSPY3IfMHPrnp2lIHpFHKlVnmVZeKUydo
2020-06-19 13:55:24,539:DEBUG:certbot.reporter:Reporting to user: Your account credentials have been saved in your Certbot configuration directory at /etc/letsencrypt. You should make a secure backup of this folder now. This configuration directory will also contain certificates and private keys obtained by Certbot so making regular backups of this folder is ideal.
2020-06-19 13:55:24,541:DEBUG:certbot.main:Picked account: <Account(RegistrationResource(body=Registration(key=JWKRSA(key=<ComparableRSAKey(<cryptography.hazmat.backends.openssl.rsa._RSAPublicKey object at 0x7fd5c3e40828>)>), contact=('mailto:tmvp91@gmail.com',), agreement=None, status='valid', terms_of_service_agreed=None, only_return_existing=None, external_account_binding=None), uri='https://acme-v02.api.letsencrypt.org/acme/acct/89244674', new_authzr_uri=None, terms_of_service='https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf'), f17fa8d41b184b1321332c2c31c39b9e, Meta(creation_dt=datetime.datetime(2020, 6, 19, 13, 55, 24, tzinfo=<UTC>), creation_host='6102584403b0'))>
2020-06-19 13:55:24,542:INFO:certbot.main:Obtaining a new certificate
2020-06-19 13:55:24,715:DEBUG:certbot.crypto_util:Generating key (2048 bits): /etc/letsencrypt/keys/0000_key-certbot.pem
2020-06-19 13:55:24,717:DEBUG:certbot.crypto_util:Creating CSR: /etc/letsencrypt/csr/0000_csr-certbot.pem
2020-06-19 13:55:24,718:DEBUG:acme.client:JWS payload:
b'{\n  "identifiers": [\n    {\n      "type": "dns",\n      "value": "134.209.199.249"\n    }\n  ]\n}'
2020-06-19 13:55:24,719:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/new-order:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvODkyNDQ2NzQiLCAibm9uY2UiOiAiMDEwMkFOZDl0Vk5LSXlIU1BZM0lmTUhQcm5wMmxJSHBGSEtsVm5tVlplS1V5ZG8iLCAidXJsIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL25ldy1vcmRlciJ9",
  "signature": "BU4kawxzGLxalIbxdxyg_hLG1-9mV8oI2YMwNW0IFhMfWjcmTNtCLVWoDrh3-aJuY3GN5XpZeGLaksxov-K9DJeQjJlUppkulaUorZ1m1fU9ZpGprJZG-q6v7u_xOY3xG3CP0ZXUs_yIGX8uODZzO5tCucKtE15-E-rogIsVS8UA17hXvY2VEtjqzpVNwYxra0ZAT_1hLH88j-7mN7qyS0Eg6O24EyRy8xqAzp-oQyK28ELk6XfcfikRjz1ag04dSZgaPocXOy3CnDC9YujbroajOvmZcrOoMhM-HGTMg2a7YWWRWMRJ59mee7MtNqtWgRniBtm_4o3NvGUAFMDTzg",
  "payload": "ewogICJpZGVudGlmaWVycyI6IFsKICAgIHsKICAgICAgInR5cGUiOiAiZG5zIiwKICAgICAgInZhbHVlIjogIjEzNC4yMDkuMTk5LjI0OSIKICAgIH0KICBdCn0"
}
2020-06-19 13:55:24,857:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/new-order HTTP/1.1" 400 221
2020-06-19 13:55:24,857:DEBUG:acme.client:Received response:
HTTP 400
Server: nginx
Date: Fri, 19 Jun 2020 13:55:24 GMT
Content-Type: application/problem+json
Content-Length: 221
Connection: keep-alive
Boulder-Requester: 89244674
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: 0102E6wxLJVGtB15up7gnXogxpXWxMJbnb42dUd21bLV_kw

{
  "type": "urn:ietf:params:acme:error:rejectedIdentifier",
  "detail": "Error creating new order :: Cannot issue for \"134.209.199.249\": The ACME server can not issue a certificate for an IP address",
  "status": 400
}
2020-06-19 13:55:24,858:DEBUG:certbot.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/bin/certbot", line 11, in <module>
    load_entry_point('certbot==0.30.2', 'console_scripts', 'certbot')()
  File "/usr/lib/python3.6/site-packages/certbot/main.py", line 1364, in main
    return config.func(config, plugins)
  File "/usr/lib/python3.6/site-packages/certbot/main.py", line 1249, in certonly
    lineage = _get_and_save_cert(le_client, config, domains, certname, lineage)
  File "/usr/lib/python3.6/site-packages/certbot/main.py", line 121, in _get_and_save_cert
    lineage = le_client.obtain_and_enroll_certificate(domains, certname)
  File "/usr/lib/python3.6/site-packages/certbot/client.py", line 410, in obtain_and_enroll_certificate
    cert, chain, key, _ = self.obtain_certificate(domains)
  File "/usr/lib/python3.6/site-packages/certbot/client.py", line 353, in obtain_certificate
    orderr = self._get_order_and_authorizations(csr.data, self.config.allow_subset_of_names)
  File "/usr/lib/python3.6/site-packages/certbot/client.py", line 385, in _get_order_and_authorizations
    orderr = self.acme.new_order(csr_pem)
  File "/usr/lib/python3.6/site-packages/acme/client.py", line 870, in new_order
    return self.client.new_order(csr_pem)
  File "/usr/lib/python3.6/site-packages/acme/client.py", line 652, in new_order
    response = self._post(self.directory['newOrder'], order)
  File "/usr/lib/python3.6/site-packages/acme/client.py", line 95, in _post
    return self.net.post(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/acme/client.py", line 1185, in post
    return self._post_once(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/acme/client.py", line 1202, in _post_once
    response = self._check_response(response, content_type=content_type)
  File "/usr/lib/python3.6/site-packages/acme/client.py", line 1054, in _check_response
    raise messages.Error.from_json(jobj)
acme.messages.Error: urn:ietf:params:acme:error:rejectedIdentifier :: Error creating new order :: Cannot issue for "134.209.199.249": The ACME server can not issue a certificate for an IP address
2020-06-19 13:55:24,859:ERROR:certbot.log:An unexpected error occurred:
2020-06-19 13:55:24,859:ERROR:certbot.log:Error creating new order :: Cannot issue for "134.209.199.249": The ACME server can not issue a certificate for an IP address
